### ISSUE TITLE
Allow to deeply copy LiquidMetal objects

### ISSUE THREAD

**Issue by panDanieleN** [newcleo-dev-team/lbh15#115]
Override `__deepcopy__` dunder method of `LiquidMetalInterface` class to allow deep copy of liquid metal onbjects when calling `copy.deepcopy`.

**Comment by lelaus** [comment]
The basic problem is that an instance of the `LiquidMetalInterface` class cannot be deeply copied by calling the `copy.deepcopy()` method. This is due to how the `__getattr__()` method is overridden: currently, a `RecursionError` arises.

As explained [here](https://stackoverflow.com/questions/47299243/recursionerror-when-python-copy-deepcopy), this happens because, when an object is copied, the `__init__` method is not called, but a new empty object is created, which has an empty `__dict__` attribute. When the `deepcopy()` method search for the `__setstate__` attribute, it does not find it in the `__dict__`, thus triggering the call of the `__getattr__()` method. Currently, the `__getattr__()` method tries to access the `__properties` attribute, but, the `__dict__` being empty, the `__getattr__()` method is invoked again for retrieving the `__properties` attribute: this induces the beginning of the infinite recursion.

A possible solution to this issue is represented by filtering out any case where the `__getattr__()` method is called to look for any special or private attribute, including the above mentioned `__setstate__` searched by `copy.deepcopy()`. By raising an exception in this case, the right copy procedure can take place.

Another way to solve the issue is represented by modifying the procedure that takes place when the `copy.deepcopy()` method is applied over a `LiquidMetalInterface` instance. For doing this, a `__deepcopy__()` method should be added to the `LiquidMetalInterface` class, whose implementation is described [here](https://stackoverflow.com/questions/57181829/deepcopy-override-clarification) and [here](https://stackoverflow.com/questions/1500718/how-to-override-the-copy-deepcopy-operations-for-a-python-object).
In this way, when applying the `copy.deepcopy()` method, the instructions implemented within the `__deepcopy__()` method override the ones implemented within the `copy.deepcopy()` method itself, thus avoiding the issue under consideration.

**Comment by panDanieleN** [comment]
Merged into master.

Updated documentation to let the user know he cannot use a name starting with `__` for custom properties (see 0518349). As aforementioned, such naming choice is not "pythonic" and not recommended in general. Fixed docstrings to avoid depracation warnings on escape sequences as well.

No need to update tests.
