### ISSUE TITLE
Use standard values from scipy.constants

### ISSUE THREAD

**Issue by ndarmage** [newcleo-dev-team/lbh15#15]
As in the object of the issue. Standard numerical values for the physical constants must be uniquely defined once. The use of scipy.constants provides all physical constants following a QA approach.

**Comment by panDanieleN** [comment]
The original cause for which the `P_ATM` constant was defined is because of an issue in the installation pipeline of the package:

1.  we want the user to type `from lbh15 import Lead` instead of `from lbh15.lead import Lead`. To accomplish this we need to add the relative import of the class inside the init of `lbh15` package.
2. from the init of the package we imported the version and the authors of the package inside the setup.py for filling the info. Since the package requires `numpy` and `scipy` to be installed, a sort of circular dependence is created as we want those but we are already using them. We are using them since we imported information from the init which imports liquid metal classes which uses `numpy` and `scipy`.
3. To overcome the problem the import of that packages were moved from toplevel of the module to local scope.
4. Nevertheless, as the atmospheric pressure is the default argument of a lot of objects of the package the definition of `P_ATM` arose.

As the issue #22 was solved, we actually understood point 2, and avoiding that import (but still reading the necessary information) solved the installation pipeline with the possibility to remove the definition `P_ATM` and avoid usage of local scope imports (as suggested by `pylint`  [guidelines](https://pylint.readthedocs.io/en/latest/user_guide/messages/convention/import-outside-toplevel.html))

Modifications can be seen in:
- Branch: scipy_const
- commit: 09afb34c14001d3e107d7af2f5fe44fab2815388

However, both the [test_documentation](https://github.com/newcleo-dev-team/lbh15/actions/runs/4980659839) and [Sphinx build](https://github.com/newcleo-dev-team/lbh15/actions/runs/4980659849) actions failed.
The reason of the failing is still the same: in the conf.py of the docs folder an import of version (and others) is performed from `lbh15` thus requiring `scipy` to be already installed.

Therefore we can solve the issue in 2 ways:
1. Install `lbh15` before building the documentation: this requires to modify the readme of the package to inform the user that he must install the package (and thus its required ones) before trying to build the documentation.
2. look for a way read the necessary info without the import of `lbh15` as done in the setup.py

**Comment by panDanieleN** [comment]
Adopted solution 2:

_look for a way read the necessary info without the import of lbh15 as done in the setup.py_

Use function defined in `setup.py` (see commit 16c1b68) to read package information (version, author and company) inside the documentation as well.

**Comment by panDanieleN** [comment]
- Modified documentation: show usage of `scipy.constants.atm` instead of `lbh15.P_ATM` (09afb34c14001d3e107d7af2f5fe44fab2815388).
- Modified tests: usage of  `scipy.constants.atm` instead of `lbh15.P_ATM` for custom properties (09afb34c14001d3e107d7af2f5fe44fab2815388)

**Comment by panDanieleN** [comment]
Merged into master. Updated tests and documentation as described in previous comment.
