### ISSUE TITLE
provide pyproject.toml 

### ISSUE THREAD

**Issue by ndarmage** [newcleo-dev-team/lbh15#22]
Please provide the file pyproject.toml to improve package install and distribution.

**Comment by CLargeron** [comment]
The latter commit concerns : 
- the automatic creation of setup.cfg from the setup.py with setuptools-py2cfg 
- the automatic creation of pyproject.toml from setup.cfg with ini2toml

This replaces the old setup.cfg and pyproject.toml written by hand

**Comment by CLargeron** [comment]
**How to install a Python project ?** 
- with setup.py : pip install -e <folder>
- with pyproject.toml : python -m pip install .

**Why using pyproject.toml ?** 
pyproject.toml is the new unified Python project settings file, specified file format of [PEP 518](https://www.python.org/dev/peps/pep-0518/) and  [PEP 517](https://peps.python.org/pep-0517/) which contains the build system requirements of Python projects. It can replace setup.py
However, editable install still need a setup.py. It is also needed if we want to use pip. 
For this reason, we keep both. It is also useful for older python version. 

**What about setup.cfg ?** 
setup.cfg concerns the configuration of the setup.py 
In the past we would have written a setup.py file which contained a bunch of configuration information but now we should put that configuration information into setup.cfg which is effectively an ini format file (i.e. does not need to be executed to be read). This is why we now have the minimal setup.py file.
The setup.py and setup.cfg files are artefacts of the setuptools module which is designed to help with the packaging process. 

**At the end, what do we want ?** 
Since setup.py is needed to install the package by using pip we want to keep it 
Since setup.cfg was created to simplify the configuration of setup.py and is useful for the packaging process, we want to keep it. 
Since pyproject.toml is the new way of project settings, we want to keep it. Even if it requires python users to change their habits :) Don't worry we keep all the setup configurations for you!

**Comment by CLargeron** [comment]
Latter commit to correct the author settings

**Comment by panDanieleN** [comment]
Defined pyproject.toml:
branch: toml_settings
commit: 8c1612aec2e40f70198073c79c8877ba28cef84c

Fixed relative import of version, added dynamic versioning in pyproject.toml and remove setup.cfg:
branch: toml_settings_dp
commit: f146601a20d39146cec0494da6709650be047f8a

**Comment by panDanieleN** [comment]
Merged into master.

Defined action in main.yml to test legacy installation when push on master.
