### ISSUE TITLE
Use the tex corporate class when generating the pdf documenatation

### ISSUE THREAD

**Issue by panDanieleN** [newcleo-dev-team/lbh15#24]
Use the [corporate tex class](https://github.com/newcleo-dev-team/nwcldocs) when generating the pdf documentation. Please use the techdoc option to prepare the manual or technical document of lbh15.

The class shall be used if found among available installed latex classes, otherwise the building must switch to default sphinx one

**Comment by CLargeron** [comment]
**Goal of this issue**

The generation of the pdf documentation is made through sphinx. 
Here, the idea is to use the [corporate tex class](https://github.com/newcleo-dev-team/nwcldocs) corresponding to the template of newcleo. 
This needs to overload the sphinx pagestyle with the technical document "techdoc" of the template of newcleo.  
This issue enhance a modification of the conf.py file in the docs repository of lbh15. 


**How to get the corporate tex class?**

Please refers on the README of the [corporate tex class](https://github.com/newcleo-dev-team/nwcldocs) in order to install in a formal way the template of newcleo nwcldocs.cls:
 % To install the package, copy the folder nwcldocs to (local texmf
% installation):
% ~[texlive\]\texmf-local\tex\latex\local\.
% and run mktexlsr under MikTeX or texhash if you use texlive.

**Use the right version of the tex class** 

We encourage you to made a git clone on the local texmf. Please make sure that the .git is present if you choose to copy the folder. Make sure you are using the last corporate tex class. 
For example, the correction of this issue will enhance a new version of the newcleo tex class https://github.com/newcleo-dev-team/nwcldocs/issues/3

**Comment by CLargeron** [comment]
This issue is suspended since the generation of latex is build by sphinx. 
Sphinx uses its own document class.

Sphinx provides two document classes:

    manual that is, sphinxmanual, extending the real LaTeX document class report (by default two-side with full title page);
    howto that is, sphinxhowto, extending the real LaTeX document class article (by default one-side). "howto" documents will not get appendices. Also, howtos will have a simpler title page.

Both class files (sphinxmanual.cls and sphinxhowto.cls) are copied to directory build/latex/ during rendering.

Keys that are set by other options and therefore should not be overridden are:

`'docclass' 'classoptions' 'title' 'release' 'author'`

After playing with the various options to customize the rendering, the outcome is that creating a custom document class is not the best option as most of the settings are then overridden by package sphinx on line 12 in code above. This package (file sphinx.sty) is copied as well to directory build/latex/.
