### ISSUE TITLE
"__custom_properties_path" Attribute ("_lbh15.py") Modification

### ISSUE THREAD

**Issue by lelaus** [newcleo-dev-team/lbh15#58]
- [1] convert the `__custom_properties_path` attribute type from _dict(string, dict(string, string))_ into _dict(string, list(string))_, the keys being the full paths to the folders where the modules are placed within, the values being the list of the names of the modules without the extension placed within the path represented by the corresponding key; this change is due to the fact that multiple modules can be placed within the same folder;
- [2] modify the implementation of the `set_custom_properties_path()` method in accordance with the new structure of the `__custom_properties_path` dict;
- [3] in the `__load_custom_properties()` method, remove the external if statement following to the change to the `__custom_properties_path`;

**Comment by lelaus** [comment]
Included a modification suggested by pylint

**Comment by panDanieleN** [comment]
Merged into master.

No need to update documentation and tests.

**Comment by panDanieleN** [comment]
Move `__custom_properties_path` to `_custom_properties_path` so that `Lead`, `LBE` and `Bismuth` classes override its value in their own module and class methods work with their attribute in place of `LiquidMetalInterface` one.

To correctly check such implementation, the update of `test_custom_properties` is required (see #86).

**Comment by panDanieleN** [comment]
Merged into master.

No need to update documentation, `test_custom_properties` updated (see #86).
